FROM node:7.9 AS node-build

WORKDIR /app
COPY ./gitlab-webhook-receiver/package.json /app
RUN npm install
COPY ./shared /shared/
COPY ./gitlab-webhook-receiver/ /app/
RUN npm run build


FROM node:7.9-alpine
EXPOSE 80
WORKDIR /app
COPY --from=node-build /app/package.json /app/
RUN npm install --production
COPY --from=node-build /app/dist/shared /shared/
COPY --from=node-build /app/dist/app /app/

CMD node /app/index.js
