FROM node:7.9 AS node-build

WORKDIR /app
COPY ./docker-event-watcher/package.json /app
RUN npm install

COPY ./shared /shared/
COPY ./docker-event-watcher/ /app/
RUN npm run build


FROM node:7.9-alpine
WORKDIR /app
COPY --from=node-build /app/package.json /app
RUN npm install --production
COPY --from=node-build /app/dist/app /app
COPY --from=node-build /app/dist/shared /shared
CMD node /app/index.js

