FROM node:7.9 AS node-build

WORKDIR /app
COPY ./dashboard/package.json /app
RUN npm install

COPY ./dashboard /app/
COPY ./shared /shared
RUN npm run ng build --prod


FROM node:7.9-alpine
WORKDIR /app
COPY --from=node-build /app/package.json /app
RUN npm install --production
COPY --from=node-build /shared /shared
COPY --from=node-build /app/server /app/server
COPY --from=node-build /app/dist/ /app/dist
CMD node /app/server/index.js

